import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "@/store/provider";
import { SidebarProvider } from "@/context/SidebarProvider";
import { ModalProvider } from "@/context/ModalProvider";
import { BottomBarProvider } from "@/context/BottomBarProvider";
import { ProfileProvider } from "@/context/ProfileProvider";
import { LanguageProvider } from "@/context/LanguageProvider";
import LayoutContent from "@/components/LayoutContent";

const montserrat = Montserrat({
  subsets: ["latin"], // Specify the character subsets you need
  weight: ["400", "700"], // Define the weights you want to use
  variable: "--font-montserrat", // Optional: Define a CSS variable for easier use with Tailwind CSS
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  appleWebApp: { capable: true, statusBarStyle: "black-translucent" }
};

// export const viewport = {
//   themeColor: "#0E141C",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Android / Chrome / Edge theme color */}
        <meta name="theme-color" content="#0E141C" />
      </head>
      <body className={`${montserrat.className}  antialiased`}>
        <StoreProvider>
          <SidebarProvider>
            <ModalProvider>
              <BottomBarProvider>
                <ProfileProvider>
                  <LanguageProvider>
                    <LayoutContent>
                      {children}
                    </LayoutContent>
                  </LanguageProvider>
                </ProfileProvider>
              </BottomBarProvider>
            </ModalProvider>
          </SidebarProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
